services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports: 
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flooddb

  gateway:
    build:
      context: ./services/gateway
    env_file:
      - .env
    ports:
      - "8000:8000"

  auth:
    build:
      context: ./services/auth
    ports:
      - "8001:8000"

  etl:
    build:
      context: ./services/etl
    env_file:
      - .env
    ports:
      - "8002:8000"

  # model:
  #   build:
  #     context: ./services/ml
  #   ports:
  #     - "8003:8000"